# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "1.0.0"
  title: OBXMLS API

# Describe your paths here
paths:
  /listing:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets `Listing` objects.
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: offset
          in: query
          description: Starting from for paging
          required: false
          type: integer
          format: int32
        -
          name: limit
          in: query
          description: Number of Listingsfor paging
          required: false
          type: integer
          format: int32
        -
          name: class
          in: query
          description: class of listing (residential, commercial, land)
          required: false
          type: string
        -
          name: price
          in: query
          description: price of home
          required: false
          type: number
          format: double
        -
          name: bedrooms
          in: query
          description: number of bedrooms
          required: false
          type: integer
          format: int32
        - 
          name: bathrooms
          in: query
          description: number of bathrooms
          required: false
          type: integer
          format: int32
        -
          name: type
          in: query
          description: The type of property for sale. Options vary depending on class. (single family home, condo, office, etc)
          required: false
          type: string
        -
          name: area
          in: query
          description: listing area
          required: false
          type: string
        -
          name: listing_date
          in: query
          description: date of listing
          required: false
          type: string 
          format: date
        -
          name: waterfront_location
          in: query
          description: waterfront location (oceanfront, pondfront, canalfront, etc)
          required: false
          type: string
        -
          name: property_location
          in: query
          description: Property locations (semi-oceanfront, 2 - lots oceanfront, semi-soundfront, etc)
          required: false
          type: string
        -
          name: status
          in: query
          description: Status of property (active, sold co-op by member, sold in house, etc) 
          required: false
          type: string
        - 
          name: bank_owned
          in: query
          description: Whether a property is owned by the bank or not
          required: false
          type: boolean
        -
          name: shortsale
          in: query
          description: Whether a property is potentially available for shortsale
          required: false
          type: boolean
        -
          name: subdivision
          in: query
          description: What subdivision a property is on
          required: false
          type: string
          
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            type: array
            items:
              $ref: '#/definitions/Listing'
  /listing/residential:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets `Listing` objects.
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: offset
          in: query
          description: Starting from for paging
          required: false
          type: number
          format: double
        -
          name: limit
          in: query
          description: Number of Listingsfor paging
          required: false
          type: number
          format: double
        -
          name: class
          in: query
          description: class of listing (residential, commercial, land)
          required: false
          type: string
        -
          name: bedrooms
          in: query
          description: number of bedrooms
          required: false
          type: integer
          format: double
        - 
          name: bathrooms
          in: query
          description: number of bathrooms
          required: false
          type: integer
          format: double
        -
          name: type
          in: query
          description: not sure what this is
          required: false
          type: string
        -
          name: areas
          in: query
          description: listing area
          required: false
          type: string
        -
          name: listing_date
          in: query
          description: date of listing
          required: false
          type: string 
          format: date
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            type: array
            items:
              $ref: '#/definitions/Listing'
  /listing/{id}:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets `Listing` object.
      parameters:
        -
          name: id
          in: path
          description: ID of listing to return
          required: true
          type: integer
          format: int64
          
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            $ref: '#/definitions/Listing'
                  
definitions:
  Listing:
    type: object
    required:
      - id
    properties:
      id:
        type: integer
      listing_date:
        type: integer
      price:
        type: integer
      address_number:
        type: integer
      address_street:
        type: string
      city:
        type: string
      state:
        type: string
      zip:
        type: integer
      baths:
        type: integer
      half_baths:
        type: integer
      bedrooms:
        type: integer
      type:
        type: string
      class:
        type: string
      area:
        type: string
      waterfront:
        type: string
      location:
        type: string
      organization:
        type: string
      listing_agent:
        type: string
      listing_agent2:
        type: string
        
  Organization:
    type: object
  User:
    type: object